import "./globals.css";
import "swiper/css";
import { CartContextProvider } from "@/_api/cartContext";
import { QueryProvider } from "@/_components/shared/query-provider";
import { Header } from "@/_components/shared/header/header";
import localFont from "next/font/local";
import { CTAFooter } from "@/_components/shared/footer/cta-footer";
import { Footer } from "@/_components/shared/footer/footer";
import { NavigationMobile } from "@/_components/shared/header/NavigationMobile";
import Script from "next/script";
import { UserProvider } from "@/_context/user-context";
import { ToastContainer } from "react-toastify";
import { Scroll } from "@/_components/scroll-to-top";
import { CookieAlert } from "@/_components/shared/cookies";

export const metadata = {
  title: "Alesari",
  description: "Generated by create next app",
};

const old_standard = localFont({
  src: [
    {
      path: "../lib/font/oldstandard-regular.ttf",
      weight: "400",
    },
    {
      path: "../lib/font/oldstandard-bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-oldstandard",
});

const century_schoolbook = localFont({
  src: [
    {
      path: "../lib/font/century.ttf",
      weight: "400",
    },
  ],
  variable: "--font-century",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          crossOrigin="anonymous"
          src="https://kit.fontawesome.com/f141ac3909.js"
        />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </head>
      <body
        className={`${old_standard?.variable} ${century_schoolbook?.variable} !min-h-dvh`}
      >
        <CartContextProvider>
          <UserProvider>
            <QueryProvider>
              <Header />
              <NavigationMobile />
              {children}
              <CTAFooter />
              <Footer />
            </QueryProvider>
          </UserProvider>
        </CartContextProvider>
        <Scroll />
        <CookieAlert />
      </body>
    </html>
  );
}
